# file containing model defininition in dict

model_name_dict = {
    'deit_base_patch16_224' : {'type': 'deit_base_b16_224', 'kwargs': {'drop_path': 0.0, 'dropout': 0.0, 'attention_dropout': 0.0, 'qkv_bias': True}}, 
    'deit_small_patch16_224': {'type': 'deit_small_b16_224', 'kwargs': {'drop_path': 0.0, 'dropout': 0.0, 'attention_dropout': 0.0, 'qkv_bias': True}}, 
    'deit_tiny_patch16_224': {'type': 'deit_tiny_b16_224', 'kwargs': {'drop_path': 0.0, 'dropout': 0.0, 'attention_dropout': 0.0, 'qkv_bias': True}}, 
    'densenet121': {'type': 'densenet121', 'kwargs': {'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'densenet169': {'type': 'densenet169', 'kwargs': {'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'densenet201': {'type': 'densenet201', 'kwargs': {'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'efficientnet_b0': {'type': 'efficientnet_b0', 'kwargs': {'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'efficientnet_b1': {'type': 'efficientnet_b1', 'kwargs': {'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'efficientnet_b2': {'type': 'efficientnet_b2', 'kwargs': {'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'efficientnet_b3': {'type': 'efficientnet_b3', 'kwargs': {'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'efficientnet_b4': {'type': 'efficientnet_b4', 'kwargs': {'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'efficientnet_b5': {'type': 'efficientnet_b5', 'kwargs': {'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'efficientnet_b6': {'type': 'efficientnet_b6', 'kwargs': {'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'efficientnet_b7': {'type': 'efficientnet_b7', 'kwargs': {'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'mixer_b16_224': {'type': 'mixer_b16_224', 'kwargs': {'drop_path': 0.0, 'drop_path_rate': 0.0}}, 
    'mixer_L16_224': {'type': 'mixer_L16_224', 'kwargs': {'drop_path': 0.0, 'drop_path_rate': 0.0}}, 
    'mobilenet_v2_x0_5': {'type': 'mobilenet_v2', 'kwargs': {'scale': 0.5, 'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'mobilenet_v2_x0_75': {'type': 'mobilenet_v2', 'kwargs': {'scale': 0.75, 'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'mobilenet_v2_x1_0': {'type': 'mobilenet_v2', 'kwargs': {'scale': 1.0, 'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'mobilenet_v2_x1_4': {'type': 'mobilenet_v2', 'kwargs': {'scale': 1.4, 'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'mobilenet_v3_large_x0_5': {'type': 'mobilenet_v3', 'kwargs': {'scale': 0.5, 'dropout': 0.0, 'mode': 'large', 'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'mobilenet_v3_large_x0_35': {'type': 'mobilenet_v3', 'kwargs': {'scale': 0.35, 'dropout': 0.0, 'mode': 'large', 'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'mobilenet_v3_large_x0_75': {'type': 'mobilenet_v3', 'kwargs': {'scale': 0.75, 'dropout': 0.0, 'mode': 'large', 'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'mobilenet_v3_large_x1_0': {'type': 'mobilenet_v3', 'kwargs': {'scale': 1.0, 'dropout': 0.0, 'mode': 'large', 'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'mobilenet_v3_large_x1_4': {'type': 'mobilenet_v3', 'kwargs': {'scale': 1.4, 'dropout': 0.0, 'mode': 'large', 'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'regnetx_400m': {'type': 'regnetx_400m', 'kwargs': {'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'regnetx_800m': {'type': 'regnetx_800m', 'kwargs': {'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'regnetx_1600m': {'type': 'regnetx_1600m', 'kwargs': {'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'regnetx_3200m': {'type': 'regnetx_3200m', 'kwargs': {'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'regnetx_6400m': {'type': 'regnetx_6400m', 'kwargs': {'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'repvgg_A0': {'type': 'repvgg_A0', 'kwargs': {'deploy': False, 'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'repvgg_B3': {'type': 'repvgg_B3', 'kwargs': {'deploy': False, 'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'resnet18': {'type': 'resnet18_official', 'kwargs': {'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'resnet34': {'type': 'resnet34_official', 'kwargs': {'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'resnet50': {'type': 'resnet50_official', 'kwargs': {'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'resnet101': {'type': 'resnet101_official', 'kwargs': {'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'resnet152': {'type': 'resnet152_official', 'kwargs': {'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'resnext50_32x4d': {'type': 'resnext50_32x4d', 'kwargs': {'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'resnext101_32x8d': {'type': 'resnext101_32x8d', 'kwargs': {'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'shufflenetv2_0.5': {'type': 'shufflenet_v2_x0_5', 'kwargs': {'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'shufflenetv2_1.0': {'type': 'shufflenet_v2_x1_0', 'kwargs': {'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'shufflenetv2_1.5': {'type': 'shufflenet_v2_x1_5', 'kwargs': {'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'shufflenetv2_2.0': {'type': 'shufflenet_v2_x2_0', 'kwargs': {'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'vit_base_patch16_224': {'type': 'vit_b16_224', 'kwargs': {'drop_path': 0.0, 'dropout': 0.0, 'attention_dropout': 0.0, 'qkv_bias': True, 'representation_size': 768}}, 
    'vit_base_patch32_224': {'type': 'vit_b32_224', 'kwargs': {'drop_path': 0.0, 'dropout': 0.0, 'attention_dropout': 0.0, 'qkv_bias': True, 'representation_size': 768}}, 
    'wide_resnet50_2': {'type': 'wide_resnet50_2', 'kwargs': {'bn': {'use_sync_bn': False, 'kwargs': {}}}}, 
    'wide_resnet101_2': {'type': 'wide_resnet101_2', 'kwargs': {'bn': {'use_sync_bn': False, 'kwargs': {}}}}
}
