default_kwargs = {
    'img_size': 224,
    'patch_size': 16,
    'in_chans': 3,
    'num_classes': 1000,
    'embed_dim': 768,
    'depth': 12,
    'mlp_ratio': 4.,
    'num_heads': 12,
    'qkv_bias': True,
    'representation_size': None,
    'drop_rate': 0.,
    'attn_drop_rate': 0.1,
    'drop_path_rate': 0.,
}
